a=(int(input("Enter a number"))
b=(int(input("Enter a number"))
print("Arithmetic operations")
print("---------------"")
print("addtion \t=\t",a+b)
print("subtraction \t=\t",a-b)
print("multiplication \t=\t",a*b)
print("division \t=\t",a/b)
print("modulo division \t=\t",a%b)
